//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ivradms
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCrearReclamo", Namespace="10.248.87.162")]
    public partial class ResultadoCrearReclamo : object
    {
        
        private string NUMERO_RECLAMOField;
        
        private string REITERACIONESField;
        
        private string NUMERO_ERRORField;
        
        private string MENSAJE_ERRORField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NUMERO_RECLAMO
        {
            get
            {
                return this.NUMERO_RECLAMOField;
            }
            set
            {
                this.NUMERO_RECLAMOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string REITERACIONES
        {
            get
            {
                return this.REITERACIONESField;
            }
            set
            {
                this.REITERACIONESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NUMERO_ERROR
        {
            get
            {
                return this.NUMERO_ERRORField;
            }
            set
            {
                this.NUMERO_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MENSAJE_ERROR
        {
            get
            {
                return this.MENSAJE_ERRORField;
            }
            set
            {
                this.MENSAJE_ERRORField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="..::IVR AES EL SALVADOR::..Soap", Namespace="10.248.87.162", ConfigurationName="ivradms.IVRAESELSALVADORSoap")]
    public interface IVRAESELSALVADORSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="10.248.87.162/CrearReclamo", ReplyAction="*")]
        System.Threading.Tasks.Task<ivradms.CrearReclamoResponse> CrearReclamoAsync(ivradms.CrearReclamoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearReclamoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearReclamo", Namespace="10.248.87.162", Order=0)]
        public ivradms.CrearReclamoRequestBody Body;
        
        public CrearReclamoRequest()
        {
        }
        
        public CrearReclamoRequest(ivradms.CrearReclamoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="10.248.87.162")]
    public partial class CrearReclamoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_NIC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_ORIGEN_RECLAMO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_TIPO_RECLAMO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_COMENTARIO_RECLAMO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string P_COMENTARIO_DIRECCION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string P_PELIGRO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string P_VECINOS_AFECTADOS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string P_EMPRESA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string P_DEPARTAMENTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string P_MUNICIPIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string P_USUARIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string P_NOMBRE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string P_TELEFONO;
        
        public CrearReclamoRequestBody()
        {
        }
        
        public CrearReclamoRequestBody(string P_NIC, string P_ORIGEN_RECLAMO, string P_TIPO_RECLAMO, string P_COMENTARIO_RECLAMO, string P_COMENTARIO_DIRECCION, string P_PELIGRO, string P_VECINOS_AFECTADOS, string P_EMPRESA, string P_DEPARTAMENTO, string P_MUNICIPIO, string P_USUARIO, string P_NOMBRE, string P_TELEFONO)
        {
            this.P_NIC = P_NIC;
            this.P_ORIGEN_RECLAMO = P_ORIGEN_RECLAMO;
            this.P_TIPO_RECLAMO = P_TIPO_RECLAMO;
            this.P_COMENTARIO_RECLAMO = P_COMENTARIO_RECLAMO;
            this.P_COMENTARIO_DIRECCION = P_COMENTARIO_DIRECCION;
            this.P_PELIGRO = P_PELIGRO;
            this.P_VECINOS_AFECTADOS = P_VECINOS_AFECTADOS;
            this.P_EMPRESA = P_EMPRESA;
            this.P_DEPARTAMENTO = P_DEPARTAMENTO;
            this.P_MUNICIPIO = P_MUNICIPIO;
            this.P_USUARIO = P_USUARIO;
            this.P_NOMBRE = P_NOMBRE;
            this.P_TELEFONO = P_TELEFONO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearReclamoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearReclamoResponse", Namespace="10.248.87.162", Order=0)]
        public ivradms.CrearReclamoResponseBody Body;
        
        public CrearReclamoResponse()
        {
        }
        
        public CrearReclamoResponse(ivradms.CrearReclamoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="10.248.87.162")]
    public partial class CrearReclamoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ivradms.ResultadoCrearReclamo CrearReclamoResult;
        
        public CrearReclamoResponseBody()
        {
        }
        
        public CrearReclamoResponseBody(ivradms.ResultadoCrearReclamo CrearReclamoResult)
        {
            this.CrearReclamoResult = CrearReclamoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IVRAESELSALVADORSoapChannel : ivradms.IVRAESELSALVADORSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class VRAESELSALVADORSoapClient : System.ServiceModel.ClientBase<ivradms.IVRAESELSALVADORSoap>, ivradms.IVRAESELSALVADORSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VRAESELSALVADORSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(VRAESELSALVADORSoapClient.GetBindingForEndpoint(endpointConfiguration), VRAESELSALVADORSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VRAESELSALVADORSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VRAESELSALVADORSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VRAESELSALVADORSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VRAESELSALVADORSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VRAESELSALVADORSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ivradms.CrearReclamoResponse> ivradms.IVRAESELSALVADORSoap.CrearReclamoAsync(ivradms.CrearReclamoRequest request)
        {
            return base.Channel.CrearReclamoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ivradms.CrearReclamoResponse> CrearReclamoAsync(string P_NIC, string P_ORIGEN_RECLAMO, string P_TIPO_RECLAMO, string P_COMENTARIO_RECLAMO, string P_COMENTARIO_DIRECCION, string P_PELIGRO, string P_VECINOS_AFECTADOS, string P_EMPRESA, string P_DEPARTAMENTO, string P_MUNICIPIO, string P_USUARIO, string P_NOMBRE, string P_TELEFONO)
        {
            ivradms.CrearReclamoRequest inValue = new ivradms.CrearReclamoRequest();
            inValue.Body = new ivradms.CrearReclamoRequestBody();
            inValue.Body.P_NIC = P_NIC;
            inValue.Body.P_ORIGEN_RECLAMO = P_ORIGEN_RECLAMO;
            inValue.Body.P_TIPO_RECLAMO = P_TIPO_RECLAMO;
            inValue.Body.P_COMENTARIO_RECLAMO = P_COMENTARIO_RECLAMO;
            inValue.Body.P_COMENTARIO_DIRECCION = P_COMENTARIO_DIRECCION;
            inValue.Body.P_PELIGRO = P_PELIGRO;
            inValue.Body.P_VECINOS_AFECTADOS = P_VECINOS_AFECTADOS;
            inValue.Body.P_EMPRESA = P_EMPRESA;
            inValue.Body.P_DEPARTAMENTO = P_DEPARTAMENTO;
            inValue.Body.P_MUNICIPIO = P_MUNICIPIO;
            inValue.Body.P_USUARIO = P_USUARIO;
            inValue.Body.P_NOMBRE = P_NOMBRE;
            inValue.Body.P_TELEFONO = P_TELEFONO;
            return ((ivradms.IVRAESELSALVADORSoap)(this)).CrearReclamoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration._x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration._x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration._x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.248.87.162/WS_RECLAMOS/ivr.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration._x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.248.87.162/WS_RECLAMOS/ivr.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            _x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap,
            
            _x002E___x003A__x003A_IVR_x0020_AES_x0020_EL_x0020_SALVADOR_x003A__x003A___Soap12,
        }
    }
}
